on:
  push:
    paths:
      - 'packages/**'
    branches: [main]
  pull_request:
    paths:
      - 'packages/**'
    branches: [main]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24.4.1
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build
        working-directory: packages/toro-router
        run: pnpm build

      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest

      - name: Run Biome
        run: biome ci .

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24.4.1
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        working-directory: packages/toro-router
        run: pnpm test

